blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://discord.com/invite/unieai
    about: Please join our Discord server for help using Unieai
  - name: Troubleshooting
    url: https://github.com/nctu6/unieai/blob/main/docs/faq.md#faq
    about: See the FAQ for common issues and solutions
