---
apiVersion: v1
kind: Namespace
metadata:
  name: unieai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unieai
  namespace: unieai
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: unieai
  template:
    metadata:
      labels:
        name: unieai
    spec:
      containers:
      - name: unieai
        image: unieai/unieai:latest
        env:
        - name: PATH
          value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: unieai
  namespace: unieai
spec:
  type: ClusterIP
  selector:
    name: unieai
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
